### ISSUE TITLE
Error: Cannot find module 'express-handlebars'

### ISSUE THREAD

**Issue by arushgupta123** [bradtraversy/nodecontactform#4]
**This is what I get When I download, extract and type node app to run**

module.js:549
    throw err;
    ^

Error: Cannot find module 'express-handlebars'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\nam,e\Downloads\nodecontactform-master\nodecontactform-master\app.js:3:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by helenzhangyc** [comment]
You probably have not installed express-handlebars. Try
`npm i express-handlebars`
